name: CI
on:
  pull_request:
    branches:
      - main

concurrency:
  group: ci-build-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15.0
      - name: Run sbt Tests
        run: 'sbt test'
      - name: Run Maven Tests
        working-directory: ./examples/java
        run: mvn --batch-mode --update-snapshots test