name: Build Main
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: openjdk@1.15.0
      - name: Lint
        run: |-
          sbt "scalafmtCheckAll;scalafmtSbtCheck"
          sbt scalastyle
      - name: Run sbt Tests
        run: 'sbt test'
      - name: Run Maven Tests
        working-directory: ./examples/java
        run: mvn --batch-mode --update-snapshots test